# Generated by Django 5.2.8 on 2025-11-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mobilerecord',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='mobilerecord',
            name='user_agent',
        ),
    ]
