# Generated by Django 5.2.8 on 2025-11-12 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_mobilerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilerecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mobile Record', 'verbose_name_plural': 'Mobile Records'},
        ),
        migrations.AddField(
            model_name='mobilerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilerecord',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
