# Generated by Django 5.2.8 on 2025-11-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_mobilerecord_options_mobilerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilerecord',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
