# Generated by Django 5.2.8 on 2025-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_mobilerecord_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilerecord',
            name='mobile',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
